### ISSUE TITLE
Screen Area Click as keybind

### ISSUE THREAD

**Issue by Haxxz** [txj-xyz/rs3-ability-tracker#33]
Mark Area on screen (say from vertices 1134,710 to 1164,780) , as a square/rectangle
left click procs keybind to show a keybound abil

In essence, keybind Left Click in screen are [input top left and bottom right coordinates] as a keybind for ability X
Might be useful for people that click abilities

Example: 
Keybind [ 1134, 710 to 1164, 780 ] as Keybind for Omnipower
user clicks on coordinates 1150, 750
Tracker displays Omnipower

**Comment by txj-xyz** [comment]
This is possible with `.on(event: 'click', listener: (e: UiohookMouseEvent) => void): this`

**Comment by txj-xyz** [comment]
Archiving this for now until I get around to doing this
